### ISSUE TITLE
API Container exiting in storefront branch with flow testnet and -f flag in flow cli not working properly

### ISSUE THREAD

**Issue by HiraSiddiqui** [onflow/kitty-items#124] opened 2021-07-25 17:24 UTC
I am following the steps for Testnet Development from this link:
https://github.com/onflow/kitty-items/tree/storefront

There are two problems I am facing with the testnet commands: 
(1) the kitty-items_api container shuts down each time 
(2) the flow project deploy command doesn't correctly parse the file with the -f flags.

**1) The kitty-items_api container problem**

When I run this command: 
`npm run start:testnet `
3 containers are created initially, the kitty-items_web, the kitty-items_api and postgres. However, within a few seconds the api containers exits.

These are the logs:
```
> kitty-items-api@0.0.1 dev /api
> tsnd src/index.ts --respawn --dev

[INFO] 17:31:51 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitty-items-api@0.0.1 dev: tsnd src/index.ts --respawn --dev
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kitty-items-api@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-23T17_31_55_331Z-debug.log

```
**(2) The Flow CLI problem**

When I run the following command:

`flow project deploy --network testnet -f flow.json -f flow.testnet.json`

I get the following error:
`:x: Config Error: deployment contains nonexisting network testnet`

I was able to fix this error by merging the following contents of flow.testnet.json into the flow.json file:

```
  "accounts": {
    "emulator-account": {
      "address": "f8d6e0586b0a20c7",
      "keys": "f8e188e8af0b8b414be59c4a1a15cc666c898fb34d94156e9b51e18bfde754a5"
    },
    "testnet-account": {
      "address": "${FLOW_ADDRESS}",
      "keys": "${FLOW_PRIVATE_KEY}"
    }
  },
  "deployments": {
    "emulator": {
      "emulator-account": [
        "Kibble",
        "KittyItems",
        "NonFungibleToken",
        "NFTStorefront"
      ]
    },
    "testnet": {
      "testnet-account": [
        "Kibble",
        "KittyItems",
        "NFTStorefront"
      ]
    }
```
Looking forward to any tips on solving these issues.

**Comment by 10thfloor** [comment] 2021-08-03 18:47
Nice! Glad you're testing out the branch! 
We'll be moving this into production soon. Will include a fix for this.

**Comment by sschulz-t** [comment] 2021-08-12 14:56
A quick "hacky" fix for problem number 2:
```
jq -s '.[0] * .[1]' flow.json flow.testnet.json > merge.json
flow project deploy --network testnet -f merge.json
```

**Comment by 10thfloor** [comment] 2021-08-19 18:35
There seems to be a regression in the `flow-cli`. We're looking into it today.

**Comment by 10thfloor** [comment] 2021-09-27 20:50
The regression has been fixed.

**Closed by 10thfloor** 2021-09-27 20:50 UTC
Labels: bug, feedback
