### ISSUE TITLE
Item listed on marketplace does not appear in marketplace listings

### ISSUE THREAD

**Issue by PeterArbaugh** [onflow/kitty-items#173] opened 2022-01-07 21:42 UTC
**Describe the bug**
When a user sells an item, the item does not appear on the marketplace listings. It does appear on the home page.

**To Reproduce**
- Observed on testnet, but I wasn't able to reproduce in testing 1/7

**Expected behavior**
Item listed for sale should appear:
- In marketplace listings on the home page
- On the marketplace listings page

**Comment by alse** [comment] 2022-01-13 22:20
I wasn't able to reproduce this on dev and a fresh testnet install. The marketplace listings are fetched from the database, so [this comment](https://github.com/onflow/kitty-items/issues/174#issuecomment-1012561822) from #174 applies here as well.

**Comment by drenz** [comment] 2022-01-20 21:50
Can't reproduce. Closing for now.

**Closed by drenz** 2022-01-20 21:50 UTC
Labels: bug, feedback
