### ISSUE TITLE
Remove hardcoded Cadence logic

### ISSUE THREAD

**Issue by albeethekid** [onflow/kitty-items#66] opened 2021-04-22 01:28 UTC
Can Cadence source be separated out as files vs being hardcoded? 

For example:
https://github.com/onflow/kitty-items/blob/master/web/src/flow/buy-market-item.tx.js

@psiemens

**Comment by 10thfloor** [comment] 2021-05-04 17:55
Duplicate of #47 ?

**Comment by 10thfloor** [comment] 2021-05-17 22:42
Closing in favour of #47

**Closed by 10thfloor** 2021-05-17 22:42 UTC
