### ISSUE TITLE
Kitty Items web app doesn't show any items in Marketplace or Store

### ISSUE THREAD

**Issue by ayy345** [onflow/kitty-items#187] opened 2022-01-12 21:35 UTC
**Describe the bug**
After following the instructions and starting the web app at http://localhost:3001/marketplace/ 
doesn't show any items in Marketplace or Store. Clicking on other links just freezes. I thought, flow.json has all the metadata that is needed to populate the webpage. 

**To Reproduce**
Follow the instructions as in https://github.com/onflow/kitty-items#local-development

**Screenshots/Logs/Output**
If applicable, add screenshots or logs to help explain your problem.
<img width="1668" alt="Screen Shot 2022-01-12 at 1 31 11 PM" src="https://user-images.githubusercontent.com/44304884/149224558-683b2c6f-9ee3-41b9-b13c-bbf6ad54f457.png">

Developer Console:

<img width="1676" alt="Screen Shot 2022-01-12 at 3 18 24 PM" src="https://user-images.githubusercontent.com/44304884/149239776-706fd6ee-7dcf-42b3-a6b0-383d57e9aed8.png">

<img width="1674" alt="Screen Shot 2022-01-12 at 3 46 21 PM" src="https://user-images.githubusercontent.com/44304884/149240844-127e1a12-a2b5-4e83-a512-706486883720.png">

**Environment (Optional - Version, OS, Browser, etc.)** : 
Chrome Browser Version 96.0.4664.110 (Official Build) (x86_64) on macOS Big Sur
Docker Version: v20.10.8
npm Version : 8.3.0
node Version : 17.3.0

**Additional context (Optional - Anything else about the bug)**
Everything starts fine. Docker services are all running
<img width="919" alt="Screen Shot 2022-01-12 at 3 48 08 PM" src="https://user-images.githubusercontent.com/44304884/149240983-609481a1-84ff-4530-9fb7-2a5e0263fadc.png">

**Comment by alse** [comment] 2022-01-15 00:31
@ayy345 thanks for reporting this. I couldn't reproduce the freezing issue, but those console errors will be resolved by #193

You won't see any store items until you log in to the service account, initialize it, and mint an item from the admin page. To see an item in the marketplace, you'll have to purchase an item with a non-service account, then sell it.

**Closed** 2022-01-17 18:38 UTC
Labels: bug, feedback
