### ISSUE TITLE
gRPC requires HTTP/2

### ISSUE THREAD

**Issue by AnikIslam1** [onflow/kitty-items#107] opened 2021-06-27 23:43 UTC
After following the step 5. Start the Flow emulator

I get the running results of gRPC and HTTP on following ports 3569, 8080.

But when I try to hit the http url I get following error gRPC requires HTTP/2

**Comment by 10thfloor** [comment] 2021-06-29 23:18
@AnikIslam1 How are you 'hitting' the URL ?

**Comment by AnikIslam1** [comment] 2021-06-30 18:26
Flow emulator server provide a local IP, there I saw the gRPC requires

**Comment by 10thfloor** [comment] 2021-06-30 20:13
If you're creating requests manually using something like curl make sure you're including `Content-Type: application/grpc-web+proto` header?

**Comment by 10thfloor** [comment] 2021-07-02 22:36
Closing because not reproducable.

**Closed** 2021-07-02 22:36 UTC
Labels: feedback, needs documentation

**Comment by AnikIslam1** [comment] 2021-07-03 00:26
Sorry for late but I get that and its work thank you

**Comment by fontanamichele** [comment] 2021-07-15 21:42
I'm facing the same issue... I've followed all the steps in the documentation, i'm running the emulator chain and my project is on a vps, when I reach my server on chrome  I get the error on ports 3569, 8080
other ports: 
3001 display kitty logo with sign in and signup button (not working)
3000 print "not found"
8701 display  account info 
5432 page not working "the page is not sanding any data"
