### ISSUE TITLE
Dev Wallet only working if deployed manually via Flow CLI (not via Docker)

### ISSUE THREAD

**Issue by muttoni** [onflow/kitty-items#189] opened 2022-01-13 10:10 UTC
**Describe the bug**
Bug is identical to https://github.com/onflow/freshmint/issues/16, which makes me think it's a dependency versioning issue, or something to do with ARM chips.

**To Reproduce**

- Install fresh copy of Kitty Items using installation guide
- follow [local development guidelines](https://github.com/onflow/kitty-items#local-development)
- open web app (should load correctly with no errors)
- but any action related to wallet discovery on :8701 (e.g. login) fails with a 500 error. 

**Screenshots/Logs/Output**

Web app: `_app-cc3bf5ab4d4c9109.js:1 GET http://localhost:8701/api/accounts 500 (Internal Server Error)`

Dev Wallet docker output:

```
> fcl-dev-wallet@0.3.0 start

> next start


ready - started server on 0.0.0.0:8701, url: http://localhost:8701


> fcl-dev-wallet@0.3.0 start

TX:ERROR execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:

error: [Error Code: 1054] location (undefined) is not a valid location: expecting an AddressLocation, but other location types are passed

--> undefined


error: [Error Code: 1054] location (undefined) is not a valid location: expecting an AddressLocation, but other location types are passed

--> undefined
```

## Workaround/Fix

- manually stop `kitty-items_dev-wallet_1` and `kitty-items_emulator_1` from docker (see image below)
- spin up a local emulator and wallet using `flow project start-emulator ./flow.json --dev-wallet`
- redeploy contracts: `flow project deploy --network emulator`

![image](https://user-images.githubusercontent.com/27052451/149307347-f068f12a-6e71-4d63-bc8b-6b90945da3ce.png)

**Environment (Optional - Version, OS, Browser, etc.)**
- Chrome 97.0.4692.71
- macOS 12.0.1 (ARM chip, M1 Pro)
- Node 16.13.1
- npm 8.3

**Additional context (Optional - Anything else about the bug)**

Docker desktop shows a warning label `amd64` on the dev wallet and emulator images (as you can see from the image above)

**Comment by alse** [comment] 2022-01-14 00:18
@muttoni thanks for reporting this, it should be fixed in #191

**Comment by fluffywiggle** [comment] 2022-01-14 05:08
Thank you for this workaround/fix! I was able to continue onto the next steps of logging in and initializing. However, I cannot mint - it gives me this 500 error 
<img width="1424" alt="Screen Shot 2022-01-13 at 9 06 00 PM" src="https://user-images.githubusercontent.com/6555812/149454986-60773c09-8a31-4cb4-961c-ee7dfa3649ff.png">

**Comment by avpdiver** [comment] 2022-01-14 10:37
> Thank you for this workaround/fix! I was able to continue onto the next steps of logging in and initializing. However, I cannot mint - it gives me this 500 error

I got same error.

**Comment by Darkmattr23** [comment] 2022-01-14 12:36
Thanks, as above the workaround worked for me to initialize the service account but minting produces an error. Fwiw, I am on Windows 10 and do not get the [amd64] badges beside the Docker components.

**Comment by alse** [comment] 2022-01-14 15:56
I can't reproduce the error on intel mac, are you seeing anything in the api or emulator image logs? It's also worth resetting your docker images

**Comment by Darkmattr23** [comment] 2022-01-14 22:38
I can confirm that after completely rebuilding docker from scratch, I no longer get the 500 error. So far, everything seems to be working correctly on dev/emulator. Thanks guys!

**Comment by 10thfloor** [comment] 2022-02-02 23:30
Confirmed fixed!

**Closed** 2022-02-02 23:30 UTC
Labels: bug, feedback
